"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={records:[],exceptions:[],summary:null,condition:[],home:{},band:{dash:"Todas"},error:{page:1,type:"Todos",critical:"Todos"}};
const money=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:2});
const number=new Intl.NumberFormat("es-MX",{maximumFractionDigits:2});
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const uniq=(a)=>[...new Set(a.filter(v=>v!==""&&v!=null))];
const sortText=a=>a.sort((x,y)=>String(x).localeCompare(String(y),"es",{numeric:true}));
const sum=(a,k)=>a.reduce((t,r)=>t+(Number(r[k])||0),0);
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
async function load(){const man=await fetch("./data/manifest-data.json").then(r=>r.json());const chunks=await Promise.all(man.chunks.map(f=>fetch(`./data/${f}`).then(r=>r.json())));state.records=chunks.flat();[state.exceptions,state.condition,state.summary]=await Promise.all([fetch("./data/exceptions.json").then(r=>r.json()),fetch("./data/condition.json").then(r=>r.json()),fetch("./data/audit-summary.json").then(r=>r.json())]);init();}
function options(vals,selected=[],allLabel="Todos"){return `<option value="__ALL__">${allLabel}</option>`+sortText(uniq(vals)).map(v=>`<option value="${esc(v)}" ${selected.includes(String(v))?"selected":""}>${esc(v)}</option>`).join("")}
function selected(el){const vals=[...el.selectedOptions].map(o=>o.value);return vals.includes("__ALL__")?[]:vals}
function filterGroup(id,label,vals,multiple=true,selectedVals=[]){return `<div class="filter-group"><label for="${id}">${label}</label><select id="${id}" ${multiple?"multiple":""}>${options(vals,selectedVals,multiple?"Todos":"Todas")}</select></div>`}
function dateValues(rows){const m=new Map();rows.forEach(r=>m.set(r.Dia,r.DiaDisplay));return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x[1])}
function dateGroup(id,label,vals){return `<div class="filter-group"><label for="${id}">${label}</label><select id="${id}">${options(vals,[],"Todas")}</select></div>`}
function init(){setupNav();buildHomeFilters();buildBandFilters();buildQuality();bindExports();renderAll();if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js");let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$("#installBtn").classList.add("hidden")}}}
function setupNav(){$$(".nav-btn").forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));const title={inicio:"Inicio",franja:"Desempeño por Franja",control:"Control de Datos"}[v];const sub={inicio:"Resumen ejecutivo de venta de artículos",franja:"Análisis por franja, tienda y artículo",control:"Calidad, excepciones y conciliación"}[v];$("#pageTitle").textContent=title;$("#pageSubtitle").textContent=sub;$("#sidebar").classList.remove("open")});$("#menuToggle").onclick=()=>$("#sidebar").classList.toggle("open")}
function buildHomeFilters(){const r=state.records;$("#homeFilters").innerHTML=filterGroup("hDM","DM",r.map(x=>x.DM))+filterGroup("hWeek","Semana",r.map(x=>x.Semana))+dateGroup("hDate","Día",dateValues(r))+filterGroup("hDayPart","DayPart",r.map(x=>x.DayPart))+filterGroup("hStore","Tienda",r.map(x=>x.Tienda))+filterGroup("hDash","Nombre Dash",r.map(x=>x.NombreDash))+`<button class="btn" id="clearHome">Limpiar filtros</button>`;$$('#homeFilters select').forEach(el=>el.onchange=renderHome);$("#clearHome").onclick=()=>{$$('#homeFilters select').forEach(s=>[...s.options].forEach(o=>o.selected=o.value==='__ALL__'));renderHome()}}
function getHome(){const f={DM:selected($("#hDM")),Semana:selected($("#hWeek")).map(Number),Dia:selected($("#hDate")),DayPart:selected($("#hDayPart")),Tienda:selected($("#hStore")),NombreDash:selected($("#hDash"))};return state.records.filter(r=>Object.entries(f).every(([k,v])=>!v.length||v.includes(r[k==='Dia'?'DiaDisplay':k])))}
function buildBandFilters(){const r=state.records;const weeks=sortText(uniq(r.map(x=>x.Semana)));$("#bandFilters").innerHTML=filterGroup("bDM","DM",r.map(x=>x.DM))+`<div class="filter-group"><label for="bWeek">Semana</label><select id="bWeek" multiple><option value="__ALL__">Todas</option><option value="__LAST__">Última semana</option>${weeks.map(v=>`<option value="${v}">${v}</option>`).join("")}</select></div>`+`<div class="filter-group"><label for="bFrom">Día desde</label><select id="bFrom">${options(dateValues(r),[],"Primera disponible")}</select></div><div class="filter-group"><label for="bTo">Día hasta</label><select id="bTo">${options(dateValues(r),[],"Última disponible")}</select></div>`+filterGroup("bDayPart","DayPart",r.map(x=>x.DayPart))+`<div class="filter-group"><label for="bStoreSearch">Buscar tienda</label><input id="bStoreSearch" type="search" placeholder="Nombre o CeCo"></div>`+filterGroup("bStore","Tienda y CeCo",r.map(x=>`${x.Tienda} · ${x.CeCo}`))+`<button class="btn" id="clearBand">Limpiar filtros</button>`;$$('#bandFilters select').forEach(el=>el.onchange=()=>{if(el.id==='bDM')refreshDependentStores();renderBand()});$('#bStoreSearch').oninput=filterStoreOptions;$("#clearBand").onclick=()=>{$$('#bandFilters select').forEach(s=>[...s.options].forEach(o=>o.selected=o.value==='__ALL__'));state.band.dash='Todas';$('#bStoreSearch').value='';renderDashButtons();refreshDependentStores();renderBand()};renderDashButtons()}
function refreshDependentStores(){const dms=selected($("#bDM"));const vals=state.records.filter(r=>!dms.length||dms.includes(r.DM)).map(x=>`${x.Tienda} · ${x.CeCo}`);$("#bStore").innerHTML=options(vals,[],"Todos");filterStoreOptions()}
function filterStoreOptions(){const q=($("#bStoreSearch")?.value||"").trim().toLocaleLowerCase("es");[...$("#bStore").options].forEach(o=>{if(o.value==="__ALL__"){o.hidden=false;return}o.hidden=q&&!o.textContent.toLocaleLowerCase("es").includes(q)})}
function renderDashButtons(){const vals=['Todas',...sortText(uniq(state.condition.map(x=>x['Nombre Dash'])))];$("#dashButtons").innerHTML=vals.map(v=>`<button class="pill ${state.band.dash===v?'active':''}" data-v="${esc(v)}">${esc(v)}</button>`).join('');$$('#dashButtons .pill').forEach(b=>b.onclick=()=>{state.band.dash=b.dataset.v;renderDashButtons();renderBand()})}
function getBand(){const dms=selected($("#bDM"));let weeks=selected($("#bWeek"));if([...$("#bWeek").selectedOptions].some(o=>o.value==='__LAST__'))weeks=[String(Math.max(...state.records.map(r=>r.Semana)))];const parts=selected($("#bDayPart"));const stores=selected($("#bStore"));const from=$("#bFrom").value,to=$("#bTo").value;const dates=dateValues(state.records);const fi=from==='__ALL__'?0:dates.indexOf(from),ti=to==='__ALL__'?dates.length-1:dates.indexOf(to);return state.records.filter(r=>(!dms.length||dms.includes(r.DM))&&(!weeks.length||weeks.includes(String(r.Semana)))&&(!parts.length||parts.includes(r.DayPart))&&(!stores.length||stores.includes(`${r.Tienda} · ${r.CeCo}`))&&(state.band.dash==='Todas'||r.NombreDash===state.band.dash)&&dates.indexOf(r.DiaDisplay)>=fi&&dates.indexOf(r.DiaDisplay)<=ti)}
function kpis(el,items){el.innerHTML=items.map(x=>`<div class="kpi"><span>${esc(x.label)}</span><strong>${esc(x.value)}</strong><small>${esc(x.note||'')}</small></div>`).join('')}
function best(rows,key,metric='VentaCalculada'){const m={};rows.forEach(r=>m[r[key]]=(m[r[key]]||0)+(Number(r[metric])||0));return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]||['—',0]}
function renderAll(){renderHome();renderBand()}
function renderHome(){const rows=getHome(),bp=best(rows,'DayPart'),bs=best(rows,'Tienda');kpis($("#homeKpis"),[{label:'Unidades vendidas',value:number.format(sum(rows,'UnidadVendida')),note:`${number.format(rows.length)} registros válidos`},{label:'Venta calculada',value:money.format(sum(rows,'VentaCalculada')),note:'Unidad × precio'},{label:'Mejor DayPart',value:bp[0],note:money.format(bp[1])},{label:'Tienda con mayor venta',value:bs[0],note:money.format(bs[1])}]);const byWeek=group(rows,'Semana','VentaCalculada');drawBars($("#weeklyChart"),byWeek.map(x=>[`Sem ${x[0]}`,x[1]]),true);const byProd=group(rows,'NombreDash','VentaCalculada').sort((a,b)=>b[1]-a[1]).slice(0,12);drawBars($("#productChart"),byProd,true);const stores=groupComposite(rows,['Tienda','DM'],'VentaCalculada').sort((a,b)=>b.value-a.value);fillStores($("#topStores"),stores.slice(0,10));fillStores($("#bottomStores"),stores.slice().sort((a,b)=>a.value-b.value).slice(0,10))}
function group(rows,key,metric){const m={};rows.forEach(r=>m[r[key]]=(m[r[key]]||0)+(Number(r[metric])||0));return Object.entries(m).sort((a,b)=>String(a[0]).localeCompare(String(b[0]),'es',{numeric:true}))}
function groupComposite(rows,keys,metric){const m=new Map();rows.forEach(r=>{const k=keys.map(x=>r[x]).join('|||');if(!m.has(k))m.set(k,{parts:keys.map(x=>r[x]),value:0});m.get(k).value+=Number(r[metric])||0});return [...m.values()]}
function fillStores(el,rows){el.innerHTML=rows.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.parts[0])}</td><td>${esc(x.parts[1])}</td><td class="num">${money.format(x.value)}</td></tr>`).join('')||'<tr><td colspan="4">Sin datos</td></tr>'}
function drawBars(el,data,currency=false){if(!data.length){el.innerHTML='<p>Sin datos para los filtros seleccionados.</p>';return}const W=760,H=Math.max(300,data.length*28+60),left=190,right=30,top=20,bottom=30,max=Math.max(...data.map(x=>x[1]),1),plot=W-left-right;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Gráfica de barras">`;data.forEach((d,i)=>{const y=top+i*28,w=d[1]/max*plot;svg+=`<text class="chart-label" x="${left-8}" y="${y+15}" text-anchor="end">${esc(String(d[0]).slice(0,27))}</text><rect class="bar" x="${left}" y="${y}" width="${w}" height="18" rx="5"></rect><text class="chart-value" x="${Math.min(left+w+6,W-70)}" y="${y+14}">${currency?money.format(d[1]):number.format(d[1])}</text>`});svg+='</svg>';el.innerHTML=svg}
function renderBand(){const rows=getBand(),bp=best(rows,'DayPart'),bs=best(rows,'Tienda');kpis($("#bandKpis"),[{label:'Unidades vendidas',value:number.format(sum(rows,'UnidadVendida'))},{label:'Venta calculada',value:money.format(sum(rows,'VentaCalculada'))},{label:'Mejor DayPart',value:bp[0],note:money.format(bp[1])},{label:'Tienda con mayor venta',value:bs[0],note:money.format(bs[1])}]);drawGrouped(rows);drawPivot(rows)}
function drawGrouped(rows){const metric=$("#metricSelect").value;const parts=sortText(uniq(rows.map(r=>r.DayPart))),prods=sortText(uniq(rows.map(r=>r.NombreDash)));if(!rows.length){$("#bandChart").innerHTML='<p>Sin datos.</p>';return}const W=900,H=390,left=55,bottom=80,top=25,right=20,plotW=W-left-right,plotH=H-top-bottom;const vals={};rows.forEach(r=>{const k=`${r.DayPart}|||${r.NombreDash}`;vals[k]=(vals[k]||0)+(Number(r[metric])||0)});const max=Math.max(...Object.values(vals),1),groupW=plotW/parts.length,barW=Math.max(5,Math.min(24,(groupW-12)/Math.max(prods.length,1)));let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let g=0;g<=4;g++){const y=top+plotH-g*plotH/4;svg+=`<line class="gridline" x1="${left}" x2="${W-right}" y1="${y}" y2="${y}"></line><text class="chart-label" x="${left-7}" y="${y+4}" text-anchor="end">${number.format(max*g/4)}</text>`}parts.forEach((p,pi)=>{prods.forEach((pr,si)=>{const v=vals[`${p}|||${pr}`]||0,h=v/max*plotH,x=left+pi*groupW+6+si*barW,y=top+plotH-h;const opacity=.45+.5*((si%5)/5);svg+=`<rect class="bar" opacity="${opacity}" x="${x}" y="${y}" width="${barW-2}" height="${h}" rx="3"><title>${esc(pr)}: ${metric==='VentaCalculada'?money.format(v):number.format(v)}</title></rect>`});svg+=`<text class="chart-label" x="${left+pi*groupW+groupW/2}" y="${H-bottom+24}" text-anchor="middle">${esc(p)}</text>`});svg+='</svg><div class="legend">'+prods.map((p,i)=>`<span><i style="background:#006241;opacity:${.45+.5*((i%5)/5)}"></i>${esc(p)}</span>`).join('')+'</div>';$("#bandChart").innerHTML=svg}
$("#metricSelect").onchange=renderBand;
function drawPivot(rows){const parts=sortText(uniq(rows.map(r=>r.DayPart))),groups=new Map();rows.forEach(r=>{const k=[r.DM,r.Tienda,r.CeCo].join('|||');if(!groups.has(k))groups.set(k,{DM:r.DM,Tienda:r.Tienda,CeCo:r.CeCo,cells:{},u:0,v:0});const g=groups.get(k),c=g.cells[r.DayPart]||(g.cells[r.DayPart]={u:0,v:0});c.u+=r.UnidadVendida;c.v+=r.VentaCalculada;g.u+=r.UnidadVendida;g.v+=r.VentaCalculada});let h='<thead><tr><th rowspan="2">DM</th><th rowspan="2">Tienda</th><th rowspan="2">CeCo</th>'+parts.map(p=>`<th colspan="2">${esc(p)}</th>`).join('')+'<th colspan="2">Total general</th></tr><tr>'+parts.map(()=>'<th class="num">Unid.</th><th class="num">Venta</th>').join('')+'<th class="num">Unid.</th><th class="num">Venta</th></tr></thead><tbody>';h+=[...groups.values()].map(g=>`<tr><td>${esc(g.DM)}</td><td>${esc(g.Tienda)}</td><td>${esc(g.CeCo)}</td>${parts.map(p=>`<td class="num">${number.format(g.cells[p]?.u||0)}</td><td class="num">${money.format(g.cells[p]?.v||0)}</td>`).join('')}<td class="num"><strong>${number.format(g.u)}</strong></td><td class="num"><strong>${money.format(g.v)}</strong></td></tr>`).join('')||'<tr><td>Sin datos</td></tr>';$("#pivotTable").innerHTML=h+'</tbody>';state.lastPivot={parts,rows:[...groups.values()]}}
function buildQuality(){const s=state.summary,c=s.exceptionCounts;const items=[['Registros totales',s.totalRecords],['Registros válidos',s.validRecords],['Registros con error',s.errorRecords],['Productos sin relación',c['Producto sin relación']||0],['Precios faltantes',(c['Precio faltante']||0)+(c['Precio no numérico']||0)],['Fechas inválidas',c['Fecha inválida']||0],['Posibles duplicados',c['Registro duplicado']||0],['Calidad de datos %',`${number.format(s.qualityPercent)}%`]];kpis($("#qualityKpis"),items.map(x=>({label:x[0],value:x[1]})));const q=s.qualityPercent,color=q>=98?'#006241':q>=95?'#b26a00':'#b3261e',cls=q>=98?'state-good':q>=95?'state-warn':'state-bad';$("#qualityState").className=cls;$("#qualityState").textContent=q>=98?'Verde':q>=95?'Amarillo':'Rojo';$("#qualityGauge").innerHTML=`<div class="gauge-ring" style="background:conic-gradient(${color} ${q*3.6}deg,#e4ebe7 0)"><strong>${number.format(q)}%</strong><span>calidad</span></div>`;const detailU=s.validUnits,dashU=sum(state.records,'UnidadVendida'),detailV=s.validSales,dashV=sum(state.records,'VentaCalculada'),du=dashU-detailU,dv=dashV-detailV,ok=Math.abs(du)<.0001&&Math.abs(dv)<.01;$("#reconState").className=ok?'state-good':'state-bad';$("#reconState").textContent=ok?'Cruce validado':'Diferencia detectada';$("#reconciliation").innerHTML=[['Total unidades detalle',number.format(detailU)],['Total unidades dashboard',number.format(dashU)],['Total monetario detalle',money.format(detailV)],['Total monetario dashboard',money.format(dashV)],['Diferencia en unidades',number.format(du)],['Diferencia en pesos',money.format(dv)]].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');buildErrorFilters();renderErrors()}
function buildErrorFilters(){const types=uniq(state.exceptions.map(e=>e['Tipo de error']));$("#errorFilters").innerHTML=`<div class="filter-group"><label>Tipo de error</label><select id="eType">${options(types,[],"Todos")}</select></div><div class="filter-group"><label>Severidad</label><select id="eCritical"><option>Todos</option><option>Crítico</option><option>No crítico</option></select></div>`;$("#eType").onchange=()=>{state.error.type=$("#eType").value;state.error.page=1;renderErrors()};$("#eCritical").onchange=()=>{state.error.critical=$("#eCritical").value;state.error.page=1;renderErrors()}}
function errorRows(){return state.exceptions.filter(e=>(state.error.type==='Todos'||state.error.type==='__ALL__'||e['Tipo de error']===state.error.type)&&(state.error.critical==='Todos'||(state.error.critical==='Crítico')===Boolean(e.Critico)))}
function renderErrors(){const all=errorRows(),size=50,pages=Math.max(1,Math.ceil(all.length/size));state.error.page=Math.min(state.error.page,pages);const rows=all.slice((state.error.page-1)*size,state.error.page*size);$("#errorTable").innerHTML=rows.map(e=>`<tr><td>${esc(e['Tipo de error'])}</td><td>${esc(e.DM)}</td><td>${esc(e.Semana)}</td><td>${esc(e.Dia)}</td><td>${esc(e.DayPart)}</td><td>${esc(e.CeCo)}</td><td>${esc(e.Tienda)}</td><td>${esc(e.Producto)}</td><td class="num">${esc(e['Unidad Vendida'])}</td><td>${esc(e['Nombre Dash'])}</td><td class="num">${esc(e['Precio Venta'])}</td><td>${esc(e['Descripción'])}</td></tr>`).join('')||'<tr><td colspan="12">Sin excepciones</td></tr>';$("#errorPager").innerHTML=`<button id="prevErr" ${state.error.page===1?'disabled':''}>Anterior</button><span>Página ${state.error.page} de ${pages} · ${all.length} errores</span><button id="nextErr" ${state.error.page===pages?'disabled':''}>Siguiente</button>`;$("#prevErr").onclick=()=>{state.error.page--;renderErrors()};$("#nextErr").onclick=()=>{state.error.page++;renderErrors()}}
function csv(rows,headers,name){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const text='\ufeff'+[headers.map(q).join(','),...rows.map(r=>headers.map(h=>q(r[h])).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function bindExports(){$("#exportErrors").onclick=()=>csv(errorRows(),['Tipo de error','DM','Semana','Dia','DayPart','CeCo','Tienda','Producto','Unidad Vendida','Nombre Dash','Precio Venta','Descripción'],'BOOST_CN_excepciones.csv');$("#exportPivot").onclick=()=>{const p=state.lastPivot||{parts:[],rows:[]},headers=['DM','Tienda','CeCo',...p.parts.flatMap(x=>[`${x} Unidades`,`${x} Venta`]),'Total Unidades','Total Venta'];const rows=p.rows.map(g=>{const o={DM:g.DM,Tienda:g.Tienda,CeCo:g.CeCo};p.parts.forEach(x=>{o[`${x} Unidades`]=g.cells[x]?.u||0;o[`${x} Venta`]=g.cells[x]?.v||0});o['Total Unidades']=g.u;o['Total Venta']=g.v;return o});csv(rows,headers,'BOOST_CN_tabla_cruzada.csv')}}
load().catch(e=>{console.error(e);$("#syncStatus").textContent='Error de carga';toast('No fue posible cargar los datos')});