"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0});
const money2=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",minimumFractionDigits:2,maximumFractionDigits:2});
const number=new Intl.NumberFormat("es-MX",{maximumFractionDigits:0});
const one=new Intl.NumberFormat("es-MX",{minimumFractionDigits:1,maximumFractionDigits:1});
const percent=new Intl.NumberFormat("es-MX",{maximumFractionDigits:1});
const state={allRows:[],rows:[],at:[],adt:[],filters:{},currentView:"inicio",metric:"Venta",productivityMetric:"TPLH",lastPivot:null,installPrompt:null,manifest:null};
const slicers=[
 {key:"Region",label:"Región"},{key:"DM",label:"DM"},{key:"Semana",label:"Semana",numeric:true},{key:"Dia",label:"Día",date:true},{key:"DayPart",label:"DayPart"},{key:"Tienda",label:"Tienda"},{key:"Item",label:"Item"}
];
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function norm(v){return String(v??"").trim().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g," ")}
function uniq(a){return [...new Set(a.filter(v=>v!==null&&v!==undefined&&v!==""))]}
function sortVals(a,numeric=false){return [...a].sort((x,y)=>numeric?Number(x)-Number(y):String(x).localeCompare(String(y),"es",{numeric:true,sensitivity:"base"}))}
function sum(rows,key){return rows.reduce((a,r)=>a+(Number(r[key])||0),0)}
function avg(rows,key){const v=rows.map(r=>Number(r[key])).filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
function compactMoney(v){return Math.abs(v)>=1e6?`$${(v/1e6).toFixed(1)}M`:Math.abs(v)>=1e3?`$${(v/1e3).toFixed(0)}k`:money.format(v)}
function fmtDate(v){if(!v)return "";const [y,m,d]=String(v).split("-");return d&&m&&y?`${d}/${m}/${y.slice(-2)}`:v}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
async function getJSON(path){const r=await fetch(path);if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
async function load(){
 state.manifest=await getJSON("./data/manifest-data.json");
 const chunks=await Promise.all(state.manifest.chunks.map(x=>getJSON(`./data/${x}`)));
 state.allRows=chunks.flat();state.rows=state.allRows.filter(r=>r.Valid!==false);
 [state.at,state.adt]=await Promise.all([getJSON("./data/base-at.json"),getJSON("./data/item-adt.json")]);
 buildSlicers();bind();restoreSettings();renderAll();
 $("#syncStatus").textContent=`${number.format(state.manifest.sourceRowsIncludingHeader)} filas Excel · ${number.format(state.rows.length)} registros`;
 const ud=state.manifest.updatedDate||"";if(ud){const [y,m,d]=ud.split("-");$("#updatedDate").textContent=`Actualizado: ${d}/${m}`;}
 if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.error);
}
function rowPasses(r,excludeKey=null){return Object.entries(state.filters).every(([k,v])=>{if(k===excludeKey)return true;if(k==="Dia"){const [a,b]=v||["",""];return(!a||r.Dia>=a)&&(!b||r.Dia<=b)}return!v?.length||v.includes(String(r[k]))})}
function filteredRows(excludeKey=null){return state.rows.filter(r=>rowPasses(r,excludeKey))}
function availableValues(key){return sortVals(uniq(state.rows.filter(r=>rowPasses(r,key)).map(r=>String(r[key]))),key==="Semana")}
function buildSlicers(){const host=$("#slicerHost");host.innerHTML=slicers.map(s=>s.date?dateSlicer(s):listSlicer(s)).join("");refreshSlicers()}
function listSlicer(s){return `<div class="slicer" data-key="${s.key}"><button class="slicer-trigger" type="button" aria-expanded="false"><small>${s.label}</small><strong>Todos</strong></button><div class="slicer-panel"><input class="slicer-search" placeholder="Buscar ${s.label.toLowerCase()}" aria-label="Buscar ${s.label}"><div class="slicer-actions"><button data-action="all">Seleccionar todo</button><button data-action="clear">Limpiar selección</button></div><div class="slicer-options"></div></div></div>`}
function dateSlicer(s){return `<div class="slicer" data-key="${s.key}"><button class="slicer-trigger" type="button" aria-expanded="false"><small>${s.label}</small><strong>Todas las fechas</strong></button><div class="slicer-panel"><div class="date-fields"><label>Desde<input type="date" data-date="from"></label><label>Hasta<input type="date" data-date="to"></label></div><div class="slicer-actions" style="margin-top:8px"><button data-action="clear">Limpiar selección</button></div></div></div>`}
function storeLabel(store){const row=state.rows.find(r=>String(r.Tienda)===String(store));return row?`${store} · ${row.CeCo}`:store}
function refreshSlicers(){
 slicers.forEach(s=>{const root=document.querySelector(`.slicer[data-key="${s.key}"]`);if(!root)return;const strong=root.querySelector("strong");
  if(s.date){const vals=availableValues("Dia"),min=vals[0]||"",max=vals.at(-1)||"",sel=state.filters.Dia||["",""];const from=root.querySelector('[data-date="from"]'),to=root.querySelector('[data-date="to"]');from.min=min;from.max=max;to.min=min;to.max=max;from.value=sel[0]||"";to.value=sel[1]||"";strong.textContent=sel[0]||sel[1]?`${fmtDate(sel[0]||min)} – ${fmtDate(sel[1]||max)}`:"Todas las fechas";return}
  const vals=availableValues(s.key),selected=state.filters[s.key]||[];root.querySelector(".slicer-options").innerHTML=vals.map(v=>`<label class="slicer-option"><input type="checkbox" value="${esc(v)}" ${selected.includes(v)?"checked":""}><span>${esc(s.key==="Tienda"?storeLabel(v):v)}</span></label>`).join("");strong.textContent=!selected.length?"Todos":selected.length===1?(s.key==="Tienda"?storeLabel(selected[0]):selected[0]):`${selected.length} seleccionados`;
 });renderFilterChips();persistSettings()
}
function renderFilterChips(){const chips=[];for(const s of slicers){const v=state.filters[s.key];if(s.date&&v&&(v[0]||v[1]))chips.push(`<span class="filter-chip">${s.label}: ${fmtDate(v[0])||"inicio"} – ${fmtDate(v[1])||"fin"}</span>`);else if(v?.length)chips.push(`<span class="filter-chip">${s.label}: ${esc(v.length<=2?v.join(", "):`${v.length} valores`)}</span>`)}$("#activeFilters").innerHTML=chips.join("")}
function persistSettings(){try{localStorage.setItem("boost-cn-v6-filters",JSON.stringify(state.filters));localStorage.setItem("boost-cn-v6-metric",state.metric);localStorage.setItem("boost-cn-v6-productivity",state.productivityMetric)}catch{}}
function restoreSettings(){try{const f=JSON.parse(localStorage.getItem("boost-cn-v6-filters")||"{}");state.filters=f&&typeof f==="object"?f:{};state.metric=localStorage.getItem("boost-cn-v6-metric")||"Venta";state.productivityMetric=localStorage.getItem("boost-cn-v6-productivity")||"TPLH";$("#globalMetric").value=state.metric;$("#bandMetric").value=state.metric;$("#productivityMetric").value=state.productivityMetric;refreshSlicers()}catch{}}
function bind(){
 $("#slicerHost").addEventListener("click",e=>{const root=e.target.closest(".slicer");if(!root)return;const key=root.dataset.key;if(e.target.closest(".slicer-trigger")){const open=root.classList.toggle("open");root.querySelector(".slicer-trigger").setAttribute("aria-expanded",open);$$('.slicer').filter(x=>x!==root).forEach(x=>x.classList.remove('open'));return}const act=e.target.closest("[data-action]")?.dataset.action;if(act){if(act==="clear")delete state.filters[key];if(act==="all")state.filters[key]=availableValues(key);refreshSlicers();renderAll();return}if(e.target.matches('input[type="checkbox"]')){const vals=[...root.querySelectorAll('input[type="checkbox"]:checked')].map(x=>x.value);if(vals.length)state.filters[key]=vals;else delete state.filters[key];refreshSlicers();renderAll()}});
 $("#slicerHost").addEventListener("input",e=>{if(e.target.matches(".slicer-search")){const q=norm(e.target.value),root=e.target.closest(".slicer");root.querySelectorAll(".slicer-option").forEach(x=>x.hidden=!norm(x.textContent).includes(q));return}if(e.target.matches('[data-date]')){const root=e.target.closest(".slicer"),a=root.querySelector('[data-date="from"]').value,b=root.querySelector('[data-date="to"]').value;if(a||b)state.filters.Dia=[a,b];else delete state.filters.Dia;refreshSlicers();renderAll()}});
 document.addEventListener("click",e=>{if(!e.target.closest(".slicer"))$$('.slicer').forEach(x=>x.classList.remove('open'))});
 $$(".nav-btn").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));
 $("#menuToggle").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
 $("#clearAll").addEventListener("click",()=>{state.filters={};refreshSlicers();renderAll();toast("Filtros limpiados")});
 $("#globalMetric").addEventListener("change",e=>{state.metric=e.target.value;$("#bandMetric").value=state.metric;persistSettings();renderAll()});
 $("#bandMetric").addEventListener("change",e=>{state.metric=e.target.value;$("#globalMetric").value=state.metric;persistSettings();renderAll()});
 $("#productivityMetric").addEventListener("change",e=>{state.productivityMetric=e.target.value;persistSettings();drawProductivity(filteredRows())});
 $("#exportPivot").addEventListener("click",exportPivot);$("#exportPdf").addEventListener("click",printDashboard);
 window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.installPrompt=e;$("#installBtn").classList.remove("hidden")});
 $("#installBtn").addEventListener("click",async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$("#installBtn").classList.add("hidden")});
}
function switchView(view){state.currentView=view;$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$("#pageTitle").textContent=view==="inicio"?"Inicio":"Desempeño por Franja";$("#pageSubtitle").textContent=view==="inicio"?"Venta y productividad en una vista ejecutiva":"Análisis por DayPart, Item y tienda";$("#sidebar").classList.remove("open");renderAll()}
function renderAll(){const rows=filteredRows();refreshSlicers();renderHome(rows);renderBand(rows)}
function best(rows,key){const m=new Map();rows.forEach(r=>m.set(r[key],(m.get(r[key])||0)+(Number(r.Venta)||0)));return [...m].sort((a,b)=>b[1]-a[1])[0]||["Sin datos",0]}
function commonKeys(rows){return new Set(rows.map(r=>`${String(r.CeCo||"")}|${r.Semana||""}|${r.Anio||""}`))}
function atRows(rows){const keys=commonKeys(rows);return state.at.filter(r=>r.Valid!==false&&keys.has(`${String(r.CeCo||"")}|${r.Semana||""}|${r.Anio||""}`))}
function adtRows(rows){const keys=new Set(rows.map(r=>`${norm(r.DM)}|${r.Semana||""}|${String(r.CeCo||"")}`));return state.adt.filter(r=>r.Valid!==false&&keys.has(`${norm(r.DM)}|${r.Semana||""}|${String(r.CeCo||"")}`))}
function atMetrics(rows){const a=atRows(rows);if(!a.length)return{real:null,ppto:null,cumpl:null};const real=avg(a,"ATR"),ppto=avg(a,"ATPpto");return{real,ppto,cumpl:ppto?real/ppto*100:null}}
function prodMetrics(rows){const a=adtRows(rows);return{tplh:avg(a,"TPLH"),adt:avg(a,"ItemADT")}}
function kpis(el,items){el.innerHTML=items.map(x=>`<article class="kpi ${x.tone||""}"><span class="label">${esc(x.label)}</span><strong class="value">${esc(x.value)}</strong>${x.note?`<span class="note">${esc(x.note)}</span>`:""}</article>`).join("")}
function renderHome(rows){
 const p=prodMetrics(rows),bd=best(rows,"DayPart"),sales=sum(rows,"Venta"),units=sum(rows,"UnidadVendida");
 kpis($("#homeKpis"),[
  {label:"Venta total",value:money.format(sales),note:`${number.format(rows.length)} registros`},
  {label:"Unidades vendidas",value:number.format(units)},
  {label:"Item/ADT",value:p.adt==null?"Sin datos":one.format(p.adt),note:"Promedio filtrado"},
  {label:"Mejor DayPart",value:bd[0],note:money.format(bd[1])}
 ]);
 const currency=state.metric==="Venta",label=currency?"$":"Unidades";
 $("#weeklyTitle").textContent=`Tendencia semanal · ${label}`;$("#weeklySubtitle").textContent=currency?"Venta calculada por semana":"Unidades vendidas por semana";$("#itemTitle").textContent=`Desempeño por Item · ${label}`;$("#dmTitle").textContent=`Venta por DM · ${label}`;
 drawAT(rows);drawProductivity(rows);drawLine($("#weeklyChart"),aggregate(rows,"Semana",state.metric).sort((a,b)=>Number(a[0])-Number(b[0])),currency);drawBars($("#itemChart"),aggregate(rows,"Item",state.metric).sort((a,b)=>b[1]-a[1]).slice(0,12),currency);drawColumns($("#dmChart"),aggregate(rows,"DM",state.metric).sort((a,b)=>b[1]-a[1]),currency);renderStores(rows)
}
function aggregate(rows,key,metric){const m=new Map();rows.forEach(r=>m.set(r[key],(m.get(r[key])||0)+(Number(r[metric])||0)));return [...m]}
function axisRange(values,zero=true){const clean=values.filter(Number.isFinite);if(!clean.length)return{min:0,max:1};let min=Math.min(...clean),max=Math.max(...clean),pad=(max-min||Math.abs(max)||1)*.12;if(zero&&min>=0)return{min:0,max:max+pad};return{min:min-pad,max:max+pad}}
function drawLine(el,data,currency=false){if(!data.length){el.innerHTML='<div class="no-data">Sin datos para la selección.</div>';return}const W=760,H=300,l=66,r=24,t=20,b=44,range=axisRange(data.map(x=>x[1]),false),xp=(W-l-r)/Math.max(data.length-1,1),yp=v=>t+(range.max-v)/(range.max-range.min||1)*(H-t-b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img">`;for(let i=0;i<5;i++){const y=t+(H-t-b)*i/4,v=range.max-(range.max-range.min)*i/4;svg+=`<line class="gridline" x1="${l}" x2="${W-r}" y1="${y}" y2="${y}"/><text class="chart-label" x="${l-7}" y="${y+4}" text-anchor="end">${currency?compactMoney(v):number.format(v)}</text>`}svg+=`<polyline class="line-real" points="${data.map((d,i)=>`${l+i*xp},${yp(d[1])}`).join(" ")}"/>`;data.forEach((d,i)=>svg+=`<circle cx="${l+i*xp}" cy="${yp(d[1])}" r="4" fill="#006241"><title>${currency?money.format(d[1]):`${number.format(d[1])} unidades`}</title></circle><text class="chart-label" x="${l+i*xp}" y="${H-15}" text-anchor="middle">Sem ${esc(d[0])}</text>`);el.innerHTML=svg+"</svg>"}
function drawAT(rows){const a=atRows(rows);if(!a.length){$("#atChart").innerHTML='<div class="no-data">Sin Base_AT para la selección.</div>';return}const by=new Map();a.forEach(r=>{if(!by.has(r.Semana))by.set(r.Semana,{real:[],aa:[],ppto:[]});const x=by.get(r.Semana);[["real",r.ATR],["aa",r.ATAA],["ppto",r.ATPpto]].forEach(([k,v])=>{v=Number(v);if(Number.isFinite(v))x[k].push(v)})});const av=v=>v.length?v.reduce((a,b)=>a+b,0)/v.length:null;const data=[...by].sort((a,b)=>a[0]-b[0]).map(([w,x])=>[w,av(x.real),av(x.aa),av(x.ppto)]);const W=760,H=300,l=68,r=22,t=18,b=42,range=axisRange(data.flatMap(x=>x.slice(1)).filter(Number.isFinite),false),xp=(W-l-r)/Math.max(data.length-1,1),yp=v=>t+(range.max-v)/(range.max-range.min||1)*(H-t-b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<5;i++){const y=t+(H-t-b)*i/4,v=range.max-(range.max-range.min)*i/4;svg+=`<line class="gridline" x1="${l}" x2="${W-r}" y1="${y}" y2="${y}"/><text class="chart-label" x="${l-7}" y="${y+4}" text-anchor="end">${money2.format(v)}</text>`}const classes=["line-real","line-aa","line-plan"],names=["AT R","AT AA","AT ppto"],colors=["#006241","#6f8f82","#85b9a4"];for(let si=1;si<=3;si++){svg+=`<polyline class="${classes[si-1]}" points="${data.filter(d=>Number.isFinite(d[si])).map(d=>`${l+data.indexOf(d)*xp},${yp(d[si])}`).join(" ")}"/>`;data.forEach((d,i)=>{if(Number.isFinite(d[si]))svg+=`<circle cx="${l+i*xp}" cy="${yp(d[si])}" r="4" fill="${colors[si-1]}"><title>${names[si-1]} ${money2.format(d[si])}</title></circle>`})}data.forEach((d,i)=>svg+=`<text class="chart-label" x="${l+i*xp}" y="${H-14}" text-anchor="middle">Sem ${d[0]}</text>`);$("#atChart").innerHTML=svg+`</svg><div class="legend"><span><i style="background:#006241"></i>AT R</span><span><i style="background:#6f8f82"></i>AT AA</span><span><i style="background:#85b9a4"></i>AT ppto</span></div>`}
function drawProductivity(rows){const a=adtRows(rows),key=state.productivityMetric,label=key==="TPLH"?"TPLH":"Item/ADT";$("#productivityTitle").textContent=`Productividad operativa · ${label}`;$("#productivitySubtitle").textContent=`${label} promedio por semana`;if(!a.length){$("#productivityChart").innerHTML='<div class="no-data">Sin datos de productividad.</div>';return}const by=new Map();a.forEach(r=>{if(!by.has(r.Semana))by.set(r.Semana,[]);const v=Number(r[key]);if(Number.isFinite(v))by.get(r.Semana).push(v)});const data=[...by].sort((a,b)=>a[0]-b[0]).map(([w,v])=>[w,v.reduce((x,y)=>x+y,0)/v.length]);const W=760,H=300,l=54,r=22,t=18,b=42,range=axisRange(data.map(x=>x[1]),false),xp=(W-l-r)/Math.max(data.length-1,1),yp=v=>t+(range.max-v)/(range.max-range.min||1)*(H-t-b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<5;i++){const y=t+(H-t-b)*i/4,v=range.max-(range.max-range.min)*i/4;svg+=`<line class="gridline" x1="${l}" x2="${W-r}" y1="${y}" y2="${y}"/><text class="chart-label" x="${l-6}" y="${y+4}" text-anchor="end">${one.format(v)}</text>`}svg+=`<polyline class="line-tplh" points="${data.map((d,i)=>`${l+i*xp},${yp(d[1])}`).join(" ")}"/>`;data.forEach((d,i)=>svg+=`<circle cx="${l+i*xp}" cy="${yp(d[1])}" r="4" fill="#006241"><title>${label} ${one.format(d[1])}</title></circle><text class="chart-label" x="${l+i*xp}" y="${H-14}" text-anchor="middle">Sem ${d[0]}</text>`);$("#productivityChart").innerHTML=svg+`</svg><div class="legend"><span><i style="background:#006241"></i>${label}</span></div>`}
function drawBars(el,data,currency=false){if(!data.length){el.innerHTML='<div class="no-data">Sin datos.</div>';return}const W=760,H=Math.max(285,data.length*27+35),left=190,right=95,top=12,plot=W-left-right,max=Math.max(...data.map(x=>x[1]),1),scale=v=>v/max*plot;let svg=`<svg viewBox="0 0 ${W} ${H}">`;data.forEach((d,i)=>{const y=top+i*25,w=Math.max(0,scale(d[1]));svg+=`<text class="chart-label" x="${left-8}" y="${y+14}" text-anchor="end">${esc(String(d[0]).slice(0,27))}</text><rect class="bar" x="${left}" y="${y}" width="${w}" height="16" rx="4"><title>${currency?money.format(d[1]):`${number.format(d[1])} unidades`}</title></rect><text class="chart-value" x="${Math.min(left+w+6,W-92)}" y="${y+13}">${currency?money.format(d[1]):number.format(d[1])}</text>`});el.innerHTML=svg+"</svg>"}
function drawColumns(el,data,currency=false){if(!data.length){el.innerHTML='<div class="no-data">Sin datos.</div>';return}const W=920,H=340,l=70,r=22,t=24,b=105,range=axisRange(data.map(x=>x[1]),true),plotW=W-l-r,plotH=H-t-b,gap=14,barW=Math.max(22,Math.min(70,(plotW-gap*(data.length+1))/Math.max(data.length,1))),yp=v=>t+(range.max-v)/(range.max-range.min||1)*plotH;let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<5;i++){const y=t+plotH*i/4,v=range.max-(range.max-range.min)*i/4;svg+=`<line class="gridline" x1="${l}" x2="${W-r}" y1="${y}" y2="${y}"/><text class="chart-label" x="${l-7}" y="${y+4}" text-anchor="end">${currency?compactMoney(v):number.format(v)}</text>`}data.forEach((d,i)=>{const slot=plotW/data.length,x=l+i*slot+(slot-barW)/2,y=yp(d[1]),h=t+plotH-y;svg+=`<rect class="bar" x="${x}" y="${y}" width="${barW}" height="${Math.max(h,1)}" rx="5"><title>${esc(d[0])}: ${currency?money.format(d[1]):`${number.format(d[1])} unidades`}</title></rect><text class="chart-value" x="${x+barW/2}" y="${Math.max(y-6,12)}" text-anchor="middle">${currency?compactMoney(d[1]):number.format(d[1])}</text><text class="chart-label dm-label" x="${x+barW/2}" y="${H-b+18}" text-anchor="end" transform="rotate(-35 ${x+barW/2} ${H-b+18})">${esc(String(d[0]).slice(0,24))}</text>`});el.innerHTML=svg+"</svg>"}
function renderStores(rows){const m=new Map(),total=sum(rows,"Venta");rows.forEach(r=>{const k=`${r.CeCo}|||${r.Tienda}`;if(!m.has(k))m.set(k,{tienda:r.Tienda,venta:0});m.get(k).venta+=Number(r.Venta)||0});const all=[...m.values()].sort((a,b)=>b.venta-a.venta);fillStores($("#topStores"),all.slice(0,10),total);fillStores($("#bottomStores"),all.slice(-10).sort((a,b)=>b.venta-a.venta),total)}
function fillStores(el,rows,total){el.innerHTML=rows.map((x,i)=>`<tr><td><span class="rank-badge">${i+1}</span></td><td>${esc(x.tienda)}</td><td class="num"><strong>${money.format(x.venta)}</strong></td><td class="num">${percent.format(total?x.venta/total*100:0)}%</td></tr>`).join("")||'<tr><td colspan="4">Sin datos</td></tr>'}
function renderBand(rows){const p=prodMetrics(rows),bp=best(rows,"DayPart");kpis($("#bandKpis"),[{label:"Unidades vendidas",value:number.format(sum(rows,"UnidadVendida"))},{label:"Venta",value:money.format(sum(rows,"Venta"))},{label:"TPLH",value:p.tplh==null?"Sin datos":one.format(p.tplh)},{label:"Item/ADT",value:p.adt==null?"Sin datos":one.format(p.adt)},{label:"Mejor DayPart",value:bp[0],note:money.format(bp[1])}]);drawGrouped(rows,state.metric);drawPivot(rows)}
function drawGrouped(rows,metric){const parts=sortVals(uniq(rows.map(r=>r.DayPart))),items=sortVals(uniq(rows.map(r=>r.Item)));if(!rows.length){$("#bandChart").innerHTML='<div class="no-data">Sin datos.</div>';return}const series=items.slice(0,8),W=920,H=390,left=68,bottom=72,top=25,right=20,plotW=W-left-right,plotH=H-top-bottom,vals={};parts.forEach(p=>series.forEach(it=>vals[`${p}|||${it}`]=sum(rows.filter(r=>r.DayPart===p&&r.Item===it),metric)));const all=Object.values(vals),range=axisRange(all,true),groupW=plotW/Math.max(parts.length,1),barW=Math.max(4,Math.min(22,(groupW-12)/Math.max(series.length,1)));let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let g=0;g<=4;g++){const y=top+plotH-g*plotH/4,v=range.min+(range.max-range.min)*g/4;svg+=`<line class="gridline" x1="${left}" x2="${W-right}" y1="${y}" y2="${y}"/><text class="chart-label" x="${left-7}" y="${y+4}" text-anchor="end">${metric==="Venta"?compactMoney(v):number.format(v)}</text>`}parts.forEach((p,pi)=>{series.forEach((it,si)=>{const v=vals[`${p}|||${it}`]||0,h=(v-range.min)/(range.max-range.min||1)*plotH,x=left+pi*groupW+6+si*barW,y=top+plotH-h;svg+=`<rect class="bar" opacity="${.45+.5*((si%5)/5)}" x="${x}" y="${y}" width="${Math.max(2,barW-2)}" height="${h}" rx="3"><title>${esc(it)}: ${metric==="Venta"?money.format(v):number.format(v)}</title></rect>`});svg+=`<text class="chart-label" x="${left+pi*groupW+groupW/2}" y="${H-bottom+25}" text-anchor="middle">${esc(p)}</text>`});$("#bandChart").innerHTML=svg+"</svg>"}
function drawPivot(rows){const parts=sortVals(uniq(rows.map(r=>r.DayPart))),groups=new Map();rows.forEach(r=>{const k=[r.DM,r.Tienda,r.CeCo].join("|||");if(!groups.has(k))groups.set(k,{DM:r.DM,Tienda:r.Tienda,CeCo:r.CeCo,cells:{},rows:[]});const g=groups.get(k);(g.cells[r.DayPart]??=[]).push(r);g.rows.push(r)});let h='<thead><tr><th rowspan="2">DM</th><th rowspan="2">Tienda</th><th rowspan="2">CeCo</th>'+parts.map(p=>`<th colspan="2">${esc(p)}</th>`).join("")+'<th colspan="2">Total general</th></tr><tr>'+parts.map(()=>'<th class="num">Unid.</th><th class="num">Venta</th>').join("")+'<th class="num">Unid.</th><th class="num">Venta</th></tr></thead><tbody>';h+=[...groups.values()].map(g=>`<tr><td>${esc(g.DM)}</td><td>${esc(g.Tienda)}</td><td>${esc(g.CeCo)}</td>${parts.map(p=>{const a=g.cells[p]||[];return `<td class="num">${number.format(sum(a,"UnidadVendida"))}</td><td class="num">${money.format(sum(a,"Venta"))}</td>`}).join("")}<td class="num"><strong>${number.format(sum(g.rows,"UnidadVendida"))}</strong></td><td class="num"><strong>${money.format(sum(g.rows,"Venta"))}</strong></td></tr>`).join("")||'<tr><td>Sin datos</td></tr>';$("#pivotTable").innerHTML=h+"</tbody>";state.lastPivot={parts,rows:[...groups.values()]}}
function exportPivot(){const p=state.lastPivot||{parts:[],rows:[]},headers=["DM","Tienda","CeCo",...p.parts.flatMap(x=>[`${x} Unidades`,`${x} Venta`]),"Total Unidades","Total Venta"],rows=p.rows.map(g=>{const o={DM:g.DM,Tienda:g.Tienda,CeCo:g.CeCo};p.parts.forEach(x=>{const a=g.cells[x]||[];o[`${x} Unidades`]=sum(a,"UnidadVendida");o[`${x} Venta`]=sum(a,"Venta")});o["Total Unidades"]=sum(g.rows,"UnidadVendida");o["Total Venta"]=sum(g.rows,"Venta");return o});csv(rows,headers,"BOOST_CN_tabla_cruzada.csv")}
function csv(rows,headers,name){const q=v=>`"${String(v??"").replace(/"/g,'""')}"`;const text='\ufeff'+[headers.map(q).join(","),...rows.map(r=>headers.map(h=>q(r[h])).join(","))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function printDashboard(){const active=$("#view-"+state.currentView),now=new Date();$$('.view').forEach(v=>v.classList.remove('print-target'));active.classList.add('print-target');const chips=[...$("#activeFilters").children].map(x=>x.textContent).join(" · ")||"Sin filtros";$("#printMeta").innerHTML=`<h1>BOOST CN · ${state.currentView==="inicio"?"Resumen ejecutivo":"Desempeño por Franja"}</h1><p>Generado: ${now.toLocaleString("es-MX")} · Métrica visual: ${state.metric==="Venta"?"$":"Unidades"} · Productividad: ${state.productivityMetric==="TPLH"?"TPLH":"Item/ADT"} · ${esc(chips)}</p>`;window.print()}
load().catch(e=>{console.error(e);$("#syncStatus").textContent="Error de carga";toast("No fue posible cargar los datos")});
