"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0});
const money2=new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",minimumFractionDigits:2,maximumFractionDigits:2});
const number=new Intl.NumberFormat("es-MX",{maximumFractionDigits:0});
const percent=new Intl.NumberFormat("es-MX",{maximumFractionDigits:1});
const state={allRows:[],rows:[],at:[],filters:{},currentView:"inicio",lastPivot:null};
const slicers=[
 {key:"Region",label:"Región"},{key:"DM",label:"DM"},{key:"Tienda",label:"Tienda"},{key:"Item",label:"Item"},
 {key:"Semana",label:"Semana",numeric:true},{key:"Dia",label:"Día",date:true},{key:"DayPart",label:"DayPart"}
];
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function uniq(a){return [...new Set(a.filter(v=>v!==null&&v!==undefined&&v!==""))]}
function sortVals(a,numeric=false){return [...a].sort((x,y)=>numeric?Number(x)-Number(y):String(x).localeCompare(String(y),"es",{numeric:true,sensitivity:"base"}))}
function sum(rows,key){return rows.reduce((a,r)=>a+(Number(r[key])||0),0)}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
async function getJSON(path){const r=await fetch(path);if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
async function load(){
 const manifest=await getJSON("./data/manifest-data.json");
 const chunks=await Promise.all(manifest.chunks.map(x=>getJSON(`./data/${x}`)));
 state.allRows=chunks.flat(); state.rows=state.allRows.filter(r=>r.Valid!==false); state.at=await getJSON("./data/base-at.json");
 buildSlicers(); bind(); renderAll();
 $("#syncStatus").textContent=`${number.format(manifest.sourceRowsIncludingHeader)} filas leídas · ${number.format(state.rows.length)} registros`;
 if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.error);
}
function rowPasses(r,excludeKey=null){
 return Object.entries(state.filters).every(([k,v])=>{
   if(k===excludeKey)return true;
   if(k==="Dia"){const [a,b]=v;return (!a||r.Dia>=a)&&(!b||r.Dia<=b)}
   return !v?.length||v.includes(String(r[k]));
 });
}
function filteredRows(){return state.rows.filter(r=>rowPasses(r))}
function availableValues(key){return sortVals(uniq(state.rows.filter(r=>rowPasses(r,key)).map(r=>String(r[key]))),key==="Semana")}
function buildSlicers(){const host=$("#slicerHost");host.innerHTML=slicers.map(s=>s.date?dateSlicer(s):listSlicer(s)).join("");refreshSlicers()}
function listSlicer(s){return `<div class="slicer" data-key="${s.key}"><button class="slicer-trigger" type="button"><small>${s.label}</small><strong>Todos</strong></button><div class="slicer-panel"><input class="slicer-search" placeholder="Buscar ${s.label.toLowerCase()}" aria-label="Buscar ${s.label}"><div class="slicer-actions"><button data-action="all">Seleccionar todo</button><button data-action="clear">Limpiar selección</button></div><div class="slicer-options"></div></div></div>`}
function dateSlicer(s){return `<div class="slicer" data-key="${s.key}"><button class="slicer-trigger" type="button"><small>${s.label}</small><strong>Todas las fechas</strong></button><div class="slicer-panel"><div class="date-fields"><label>Desde<input type="date" data-date="from"></label><label>Hasta<input type="date" data-date="to"></label></div><div class="slicer-actions" style="margin-top:8px"><button data-action="clear">Limpiar selección</button></div></div></div>`}
function refreshSlicers(){
 slicers.forEach(s=>{const root=document.querySelector(`.slicer[data-key="${s.key}"]`),trigger=root.querySelector(".slicer-trigger"),strong=trigger.querySelector("strong");
   if(s.date){const vals=availableValues("Dia"),min=vals[0]||"",max=vals.at(-1)||"",sel=state.filters.Dia||["",""];root.querySelector('[data-date="from"]').min=min;root.querySelector('[data-date="from"]').max=max;root.querySelector('[data-date="to"]').min=min;root.querySelector('[data-date="to"]').max=max;root.querySelector('[data-date="from"]').value=sel[0]||"";root.querySelector('[data-date="to"]').value=sel[1]||"";strong.textContent=sel[0]||sel[1]?`${fmtDate(sel[0]||min)} – ${fmtDate(sel[1]||max)}`:"Todas las fechas";trigger.classList.toggle("has-value",!!(sel[0]||sel[1]));return}
   const vals=availableValues(s.key),sel=state.filters[s.key]||[];root.querySelector(".slicer-options").innerHTML=vals.map(v=>`<label class="slicer-option"><input type="checkbox" value="${esc(v)}" ${sel.includes(v)?"checked":""}><span>${esc(displayValue(s.key,v))}</span></label>`).join("")||'<div class="no-data" style="min-height:70px">Sin valores disponibles</div>';
   strong.textContent=sel.length===0?"Todos":sel.length===1?displayValue(s.key,sel[0]):`${sel.length} seleccionados`;trigger.classList.toggle("has-value",sel.length>0);
 }); renderChips();
}
function displayValue(key,v){if(key==="Semana")return `Semana ${v}`;if(key==="Tienda"){const r=state.rows.find(x=>String(x.Tienda)===String(v));return r?`${v} · ${r.CeCo}`:v}return v}
function fmtDate(v){if(!v)return"";const [y,m,d]=v.split("-");return `${d}/${m}/${y.slice(2)}`}
function renderChips(){const chips=[];for(const [k,v] of Object.entries(state.filters)){if(k==="Dia"){if(v[0]||v[1])chips.push(`Día: ${fmtDate(v[0])||"inicio"} – ${fmtDate(v[1])||"fin"}`)}else if(v?.length)chips.push(`${slicers.find(s=>s.key===k)?.label||k}: ${v.length===1?displayValue(k,v[0]):v.length+" seleccionados"}`)}$("#activeFilters").innerHTML=chips.map(x=>`<span class="filter-chip">${esc(x)}</span>`).join("")}
function bind(){
 document.addEventListener("click",e=>{const root=e.target.closest(".slicer");if(e.target.closest(".slicer-trigger")){const was=root.classList.contains("open");$$('.slicer').forEach(x=>x.classList.remove("open"));if(!was)root.classList.add("open");return}if(!root)$$('.slicer').forEach(x=>x.classList.remove("open"))});
 $$(".slicer").forEach(root=>{const key=root.dataset.key,search=root.querySelector(".slicer-search");if(search)search.addEventListener("input",()=>root.querySelectorAll(".slicer-option").forEach(o=>o.hidden=!o.textContent.toLowerCase().includes(search.value.toLowerCase())));root.addEventListener("change",e=>{if(e.target.type==="checkbox"){state.filters[key]=[...root.querySelectorAll('input[type="checkbox"]:checked')].map(x=>x.value);if(!state.filters[key].length)delete state.filters[key];refreshSlicers();renderAll()}if(e.target.dataset.date){const a=root.querySelector('[data-date="from"]').value,b=root.querySelector('[data-date="to"]').value;if(a||b)state.filters.Dia=[a,b];else delete state.filters.Dia;refreshSlicers();renderAll()}});root.addEventListener("click",e=>{const a=e.target.dataset.action;if(!a)return;if(a==="clear")delete state.filters[key];if(a==="all"){const vals=availableValues(key);state.filters[key]=vals}refreshSlicers();renderAll()})});
 $$(".nav-btn").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$("#menuToggle").onclick=()=>$("#sidebar").classList.toggle("open");
 $("#clearAll").onclick=()=>{state.filters={};refreshSlicers();renderAll()};
 ["bandMetric"].forEach(id=>$("#"+id).onchange=renderAll);
 $("#exportPdf").onclick=printDashboard;$("#exportPivot").onclick=exportPivot;
}
function switchView(view){state.currentView=view;$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$("#pageTitle").textContent=view==="inicio"?"Inicio":"Desempeño por Franja";$("#pageSubtitle").textContent=view==="inicio"?"Visión ejecutiva 360° de venta y ticket":"Comparativo operativo por franja";$("#sidebar").classList.remove("open");renderAll()}
function ticketRows(rows){const dms=new Set(rows.map(r=>r.DMKey)),weeks=new Set(rows.map(r=>Number(r.Semana))),years=new Set(rows.map(r=>Number(r.Año))),regions=new Set(rows.map(r=>r.Region));return state.at.filter(a=>dms.has(a.DMKey)&&weeks.has(Number(a.Semana))&&years.has(Number(a.Año))&&regions.has(a.Region))}
function ticketMetrics(rows){const a=ticketRows(rows);if(!a.length)return{real:null,ppto:null,prom:null,dif:null,cump:null};const real=sum(a,"TicketReal")/a.length,ppto=sum(a,"TicketPresupuesto")/a.length;return{real,ppto,prom:real,dif:real-ppto,cump:ppto?real/ppto*100:null}}
function best(rows,key,metric="Venta"){const m=new Map();rows.forEach(r=>m.set(r[key],(m.get(r[key])||0)+(Number(r[metric])||0)));return [...m].sort((a,b)=>b[1]-a[1])[0]||["Sin datos",0]}
function kpis(el,items){el.innerHTML=items.map(x=>`<article class="kpi ${x.tone||""}"><div class="label">${esc(x.label)}</div><div class="value">${esc(x.value)}</div>${x.note?`<div class="note">${esc(x.note)}</div>`:""}</article>`).join("")}
function renderAll(){const rows=filteredRows();renderHome(rows);renderBand(rows)}
function renderHome(rows){const t=ticketMetrics(rows),bp=best(rows,"DayPart"),bi=best(rows,"Item"),bs=best(rows,"Tienda");kpis($("#homeKpis"),[
 {label:"Venta total",value:money.format(sum(rows,"Venta"))},{label:"Unidades vendidas",value:number.format(sum(rows,"UnidadVendida"))},{label:"Ticket Real",value:t.real==null?"Sin datos":money2.format(t.real)},
 {label:"Ticket Presupuesto",value:t.ppto==null?"Sin datos":money2.format(t.ppto)},{label:"Cumplimiento",value:t.cump==null?"Sin datos":percent.format(t.cump)+"%",tone:t.cump>=100?"positive":"negative"},
 {label:"Diferencia",value:t.dif==null?"Sin datos":money2.format(t.dif),tone:t.dif>=0?"positive":"negative"},{label:"Mejor Item",value:bi[0],note:money.format(bi[1])},
 {label:"Mejor DayPart",value:bp[0],note:money.format(bp[1])},{label:"Tienda líder",value:bs[0],note:money.format(bs[1])},{label:"Registros",value:number.format(rows.length),note:"Base filtrada"}
 ]);
 drawWeekly(rows,"Venta");drawTicket(rows,"ticket");drawBars($("#itemChart"),aggregate(rows,"Item","Venta").slice(0,10),true);drawBars($("#daypartChart"),aggregate(rows,"DayPart","Venta"),true);drawBars($("#dmChart"),aggregate(rows,"DM","Venta"),true);drawBars($("#storeChart"),aggregate(rows,"Tienda","Venta").slice(0,10),true);renderStores(rows)
}
function aggregate(rows,key,metric){const m=new Map();rows.forEach(r=>m.set(r[key],(m.get(r[key])||0)+(Number(r[metric])||0)));return [...m].sort((a,b)=>b[1]-a[1])}
function drawWeekly(rows,metric){const data=aggregate(rows,"Semana",metric).sort((a,b)=>Number(a[0])-Number(b[0]));drawLine($("#weeklyChart"),data,metric==="Venta")}
function drawLine(el,data,currency=false){if(!data.length){el.innerHTML='<div class="no-data">Sin datos para la selección.</div>';return}const W=760,H=300,l=58,r=22,t=18,b=42,vals=data.map(x=>x[1]),min=Math.min(...vals),max=Math.max(...vals),pad=(max-min||max||1)*.12,ymin=Math.max(0,min-pad),ymax=max+pad,xp=(W-l-r)/Math.max(data.length-1,1),yp=v=>t+(ymax-v)/(ymax-ymin||1)*(H-t-b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img">`;for(let i=0;i<5;i++){const y=t+(H-t-b)*i/4,v=ymax-(ymax-ymin)*i/4;svg+=`<line class="gridline" x1="${l}" x2="${W-r}" y1="${y}" y2="${y}"/><text class="chart-label" x="${l-6}" y="${y+4}" text-anchor="end">${currency?compactMoney(v):number.format(v)}</text>`}const pts=data.map((d,i)=>`${l+i*xp},${yp(d[1])}`).join(" ");svg+=`<polyline class="line-real" points="${pts}"/>`;data.forEach((d,i)=>svg+=`<circle cx="${l+i*xp}" cy="${yp(d[1])}" r="4" fill="#006241"><title>Semana ${d[0]} · ${currency?money.format(d[1]):number.format(d[1])}</title></circle><text class="chart-label" x="${l+i*xp}" y="${H-14}" text-anchor="middle">Sem ${d[0]}</text>`);el.innerHTML=svg+"</svg>"}
function drawTicket(rows,mode){if(mode==="units"){const data=aggregate(rows,"Semana","UnidadVendida").filter(x=>Number(x[0])>=28).sort((a,b)=>Number(a[0])-Number(b[0]));drawLine($("#ticketChart"),data,false);return}const a=ticketRows(rows);if(!a.length){$("#ticketChart").innerHTML='<div class="no-data">Sin Base_AT para la selección.</div>';return}const by=new Map();a.forEach(r=>{if(!by.has(r.Semana))by.set(r.Semana,{real:0,ppto:0,n:0});const x=by.get(r.Semana);x.real+=r.TicketReal||0;x.ppto+=r.TicketPresupuesto||0;x.n++});const data=[...by].sort((a,b)=>a[0]-b[0]).map(([w,x])=>[w,x.real/x.n,x.ppto/x.n]);const W=760,H=300,l=58,r=22,t=18,b=42,vals=data.flatMap(x=>x.slice(1)),min=Math.min(...vals),max=Math.max(...vals),pad=(max-min||max||1)*.12,ymin=Math.max(0,min-pad),ymax=max+pad,xp=(W-l-r)/Math.max(data.length-1,1),yp=v=>t+(ymax-v)/(ymax-ymin||1)*(H-t-b);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<5;i++){const y=t+(H-t-b)*i/4,v=ymax-(ymax-ymin)*i/4;svg+=`<line class="gridline" x1="${l}" x2="${W-r}" y1="${y}" y2="${y}"/><text class="chart-label" x="${l-6}" y="${y+4}" text-anchor="end">${money2.format(v)}</text>`}const pts=i=>data.map((d,n)=>`${l+n*xp},${yp(d[i])}`).join(" ");svg+=`<polyline class="line-real" points="${pts(1)}"/><polyline class="line-plan" points="${pts(2)}"/>`;data.forEach((d,i)=>svg+=`<circle cx="${l+i*xp}" cy="${yp(d[1])}" r="4" fill="#006241"><title>Real ${money2.format(d[1])}</title></circle><circle cx="${l+i*xp}" cy="${yp(d[2])}" r="4" fill="#8dbdad"><title>Presupuesto ${money2.format(d[2])}</title></circle><text class="chart-label" x="${l+i*xp}" y="${H-14}" text-anchor="middle">Sem ${d[0]}</text>`);const ar=data.reduce((a,d)=>a+d[1],0)/data.length,ap=data.reduce((a,d)=>a+d[2],0)/data.length,ac=ap?ar/ap*100:0;$("#ticketChart").innerHTML=svg+`</svg><div class="legend"><span><i style="background:#006241"></i>Ticket Real</span><span><i style="background:#8dbdad"></i>Ticket Ppto</span><strong>Cumplimiento ${percent.format(ac)}%</strong></div>`}
function compactMoney(v){return v>=1e6?`$${(v/1e6).toFixed(1)}M`:v>=1e3?`$${(v/1e3).toFixed(0)}k`:money.format(v)}
function drawBars(el,data,currency=false){if(!data.length){el.innerHTML='<div class="no-data">Sin datos para la selección.</div>';return}const W=760,H=Math.max(280,data.length*25+35),left=190,right=90,top=10,vals=data.map(x=>x[1]),min=Math.min(...vals),max=Math.max(...vals),base=Math.min(0,min),plot=W-left-right,scale=v=>(v-base)/(max-base||1)*plot;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img">`;data.forEach((d,i)=>{const y=top+i*25,w=scale(d[1]);svg+=`<text class="chart-label" x="${left-8}" y="${y+14}" text-anchor="end">${esc(String(d[0]).slice(0,28))}</text><rect class="bar" x="${left}" y="${y}" width="${w}" height="16" rx="4"><title>${currency?money.format(d[1]):number.format(d[1])}</title></rect><text class="chart-value" x="${Math.min(left+w+6,W-82)}" y="${y+13}">${currency?money.format(d[1]):number.format(d[1])}</text>`});el.innerHTML=svg+"</svg>"}
function renderStores(rows){const m=new Map(),weeks=sortVals(uniq(rows.map(r=>Number(r.Semana))),true),latest=weeks.at(-1),prev=weeks.at(-2),total=sum(rows,"Venta");rows.forEach(r=>{const k=`${r.Tienda}|||${r.DM}`;if(!m.has(k))m.set(k,{tienda:r.Tienda,dm:r.DM,venta:0,latest:0,prev:0});const x=m.get(k),v=Number(r.Venta)||0;x.venta+=v;if(Number(r.Semana)===latest)x.latest+=v;if(Number(r.Semana)===prev)x.prev+=v});const all=[...m.values()].sort((a,b)=>b.venta-a.venta);fillStores($("#topStores"),all.slice(0,10),total);fillStores($("#bottomStores"),all.slice(-10),total)}
function fillStores(el,rows,total){el.innerHTML=rows.map((x,i)=>{const share=total?x.venta/total*100:0,trend=x.prev?((x.latest-x.prev)/x.prev*100):null;return `<tr><td>${i+1}</td><td>${esc(x.tienda)}</td><td>${esc(x.dm)}</td><td class="num">${money.format(x.venta)}</td><td class="num">${percent.format(share)}%</td><td class="num ${trend!=null&&trend>=0?"trend-up":"trend-down"}">${trend==null?"—":`${trend>=0?"↑":"↓"} ${percent.format(Math.abs(trend))}%`}</td></tr>`}).join("")||'<tr><td colspan="6">Sin datos</td></tr>'}
function renderBand(rows){const t=ticketMetrics(rows),bp=best(rows,"DayPart"),bs=best(rows,"Tienda");kpis($("#bandKpis"),[{label:"Unidades vendidas",value:number.format(sum(rows,"UnidadVendida"))},{label:"Venta",value:money.format(sum(rows,"Venta"))},{label:"Ticket Promedio",value:t.prom==null?"Sin datos":money2.format(t.prom)},{label:"Mejor DayPart",value:bp[0],note:money.format(bp[1])},{label:"Tienda con mayor venta",value:bs[0],note:money.format(bs[1])}]);drawGrouped(rows,$("#bandMetric").value);drawPivot(rows)}
function drawGrouped(rows,metric){const parts=sortVals(uniq(rows.map(r=>r.DayPart))),items=sortVals(uniq(rows.map(r=>r.Item)));if(!rows.length){$("#bandChart").innerHTML='<div class="no-data">Sin datos.</div>';return}const series=items.slice(0,8),W=920,H=390,left=62,bottom=72,top=25,right=20,plotW=W-left-right,plotH=H-top-bottom,vals={};parts.forEach(p=>series.forEach(it=>vals[`${p}|||${it}`]=sum(rows.filter(r=>r.DayPart===p&&r.Item===it),metric)));const all=Object.values(vals),min=Math.min(...all,0),max=Math.max(...all,1),groupW=plotW/Math.max(parts.length,1),barW=Math.max(4,Math.min(22,(groupW-12)/Math.max(series.length,1)));let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let g=0;g<=4;g++){const y=top+plotH-g*plotH/4,v=min+(max-min)*g/4;svg+=`<line class="gridline" x1="${left}" x2="${W-right}" y1="${y}" y2="${y}"/><text class="chart-label" x="${left-7}" y="${y+4}" text-anchor="end">${metric==="Venta"?compactMoney(v):number.format(v)}</text>`}parts.forEach((p,pi)=>{series.forEach((it,si)=>{const v=vals[`${p}|||${it}`]||0,h=(v-min)/(max-min||1)*plotH,x=left+pi*groupW+6+si*barW,y=top+plotH-h;svg+=`<rect class="bar" opacity="${.42+.5*((si%5)/5)}" x="${x}" y="${y}" width="${Math.max(2,barW-2)}" height="${h}" rx="3"><title>${esc(it)}: ${metric==="Venta"?money.format(v):number.format(v)}</title></rect>`});svg+=`<text class="chart-label" x="${left+pi*groupW+groupW/2}" y="${H-bottom+25}" text-anchor="middle">${esc(p)}</text>`});$("#bandChart").innerHTML=svg+"</svg>"}
function drawPivot(rows){const parts=sortVals(uniq(rows.map(r=>r.DayPart))),groups=new Map();rows.forEach(r=>{const k=[r.DM,r.Tienda,r.CeCo].join("|||");if(!groups.has(k))groups.set(k,{DM:r.DM,Tienda:r.Tienda,CeCo:r.CeCo,cells:{},rows:[]});const g=groups.get(k);(g.cells[r.DayPart]??=[]).push(r);g.rows.push(r)});let h='<thead><tr><th rowspan="2">DM</th><th rowspan="2">Tienda</th><th rowspan="2">CeCo</th>'+parts.map(p=>`<th colspan="3">${esc(p)}</th>`).join("")+'<th colspan="3">Total general</th></tr><tr>'+parts.map(()=>'<th class="num">Unid.</th><th class="num">Venta</th><th class="num">Ticket</th>').join("")+'<th class="num">Unid.</th><th class="num">Venta</th><th class="num">Ticket</th></tr></thead><tbody>';h+=[...groups.values()].map(g=>`<tr><td>${esc(g.DM)}</td><td>${esc(g.Tienda)}</td><td>${esc(g.CeCo)}</td>${parts.map(p=>{const a=g.cells[p]||[],t=ticketMetrics(a).prom;return `<td class="num">${number.format(sum(a,"UnidadVendida"))}</td><td class="num">${money.format(sum(a,"Venta"))}</td><td class="num">${t==null?"—":money2.format(t)}</td>`}).join("")}<td class="num"><strong>${number.format(sum(g.rows,"UnidadVendida"))}</strong></td><td class="num"><strong>${money.format(sum(g.rows,"Venta"))}</strong></td><td class="num"><strong>${ticketMetrics(g.rows).prom==null?"—":money2.format(ticketMetrics(g.rows).prom)}</strong></td></tr>`).join("")||'<tr><td>Sin datos</td></tr>';$("#pivotTable").innerHTML=h+"</tbody>";state.lastPivot={parts,rows:[...groups.values()]}}
function exportPivot(){const p=state.lastPivot||{parts:[],rows:[]},headers=["DM","Tienda","CeCo",...p.parts.flatMap(x=>[`${x} Unidades`,`${x} Venta`,`${x} Ticket Promedio`]),"Total Unidades","Total Venta","Ticket Promedio"],rows=p.rows.map(g=>{const o={DM:g.DM,Tienda:g.Tienda,CeCo:g.CeCo};p.parts.forEach(x=>{const a=g.cells[x]||[];o[`${x} Unidades`]=sum(a,"UnidadVendida");o[`${x} Venta`]=sum(a,"Venta");o[`${x} Ticket Promedio`]=ticketMetrics(a).prom??""});o["Total Unidades"]=sum(g.rows,"UnidadVendida");o["Total Venta"]=sum(g.rows,"Venta");o["Ticket Promedio"]=ticketMetrics(g.rows).prom??"";return o});csv(rows,headers,"BOOST_CN_tabla_cruzada.csv")}
function csv(rows,headers,name){const q=v=>`"${String(v??"").replace(/"/g,'""')}"`;const text='\ufeff'+[headers.map(q).join(","),...rows.map(r=>headers.map(h=>q(r[h])).join(","))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function printDashboard(){const active=$("#view-"+state.currentView),now=new Date();$$('.view').forEach(v=>v.classList.remove('print-target'));active.classList.add('print-target');const chips=[...$("#activeFilters").children].map(x=>x.textContent).join(" · ")||"Sin filtros";$("#printMeta").innerHTML=`<h1>BOOST CN · ${state.currentView==="inicio"?"Inicio":"Desempeño por Franja"}</h1><p>Generado: ${now.toLocaleString("es-MX")} · ${esc(chips)}</p>`;window.print()}
load().catch(e=>{console.error(e);$("#syncStatus").textContent="Error de carga";toast("No fue posible cargar los datos")});
